// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeCjidAhjrNh4NTE-LZIDflHnf9Wry_b8',
    appId: '1:242454843033:web:58590b2d57840327a27208',
    messagingSenderId: '242454843033',
    projectId: 'office-task-69c52',
    authDomain: 'office-task-69c52.firebaseapp.com',
    storageBucket: 'office-task-69c52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-r480q8dcSr5EIfqr_wrTwsImMd8yUoc',
    appId: '1:242454843033:android:c960e505db676459a27208',
    messagingSenderId: '242454843033',
    projectId: 'office-task-69c52',
    storageBucket: 'office-task-69c52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATWjUihZ9qu80xx4Y_mkIQ2Etmibvf2n4',
    appId: '1:242454843033:ios:bfbf9a9cad9e6de1a27208',
    messagingSenderId: '242454843033',
    projectId: 'office-task-69c52',
    storageBucket: 'office-task-69c52.firebasestorage.app',
    iosBundleId: 'com.example.officeTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATWjUihZ9qu80xx4Y_mkIQ2Etmibvf2n4',
    appId: '1:242454843033:ios:bfbf9a9cad9e6de1a27208',
    messagingSenderId: '242454843033',
    projectId: 'office-task-69c52',
    storageBucket: 'office-task-69c52.firebasestorage.app',
    iosBundleId: 'com.example.officeTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeCjidAhjrNh4NTE-LZIDflHnf9Wry_b8',
    appId: '1:242454843033:web:6b8ede4da5402affa27208',
    messagingSenderId: '242454843033',
    projectId: 'office-task-69c52',
    authDomain: 'office-task-69c52.firebaseapp.com',
    storageBucket: 'office-task-69c52.firebasestorage.app',
  );
}
